# Generated by Django 4.2.4 on 2023-09-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0002_alter_advertisement_options_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
