# Generated by Django 4.2.4 on 2023-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0005_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(upload_to='my_adverts', verbose_name='Изображение'),
        ),
    ]
