# Generated by Django 4.2.4 on 2023-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0008_advertisement_ababa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='ababa',
        ),
    ]
